### ISSUE TITLE
Crashing if you load mame2010 before

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/mame2010-libretro#4]
Load first some rom with mame2010, then load other core (tested with mame git, genplus, vbam), wait some time and it'll crash.

Edit: I forgot to say, Ubuntu 14.04, amd64.

Edit2: you don't need wait any time, just load the second core with content, press any keyboard button and it'll crash. There's no issue with joysticks.

Mame git trace:

```
Program received signal SIGILL, Illegal instruction.
0x00007fffda6e0b41 in construct_address_map_cupsoc_mem (map=..., device=...) at src/mame/drivers/legionna.c:296
296     AM_RANGE(0x100700, 0x10071f) AM_READWRITE(sound_comms_r,sound_comms_w)
(gdb) 
(gdb) bt full
#0  0x00007fffda6e0b41 in construct_address_map_cupsoc_mem (map=..., device=...) at src/mame/drivers/legionna.c:296
        curentry = 0x7fffffffde10
#1  0x00000000000001e1 in ?? ()
No symbol table info available.
#2  0x0001010100000000 in ?? ()
No symbol table info available.
#3  0x0000000000cdc1c0 in ?? ()
No symbol table info available.
#4  0x0000000004600002 in ?? ()
No symbol table info available.
#5  0x000000000000009c in ?? ()
No symbol table info available.
#6  0x0000000000000000 in ?? ()
No symbol table info available.
```

Compiled with -O0 -g

**Comment by sergiobenrocha2** [comment]
updated with a proper backtrace to gen plus

**Comment by twinaphex** [comment]
I think this is fixed now because we removed libco and the shutdown env callback. Let me know if it still happens though.
